### PR TITLE
Some light refactors to use a data structure to hold the parsed results.

### PR DESCRIPTION
**Pull request by mattmoore**

### CODE REVIEW

**Comment by tieskedh** [comment]
little hint:
`filter { it is kastree.ast.Node.Decl.Structured }.map { it as kastree.ast.Node.Decl.Structured }
is the same as
`filterIsInstance<kastree.ast.Node.Decl.Structured>()`

**Comment by ahinchman1** [comment]
@tieskedh @mattmoore  I had no idea! This is so cool, is this a new Kotlin function?

**Comment by mattmoore** [comment]
@tieskedh @ahinchman1 Nice! I felt like I was going crazy with the need for a double transform on filters. Looks like this has been around for a little bit. Kotlin 1.2 and 1.3 has it.

**Comment by ahinchman1** [comment]
@mattmoore I think you have to rebase this PR

**Pull request closed without merging**
